name: leccionario_mobile
description: Cliente Flutter para consulta y cierre diario del leccionario.
publish_to: none
version: 0.2.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.4.0
  path: ^1.9.0
  connectivity_plus: ^6.0.5
  intl: ^0.20.2
  mobile_scanner: ^5.2.3
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
