    # ==========================================
    # 6. APLICACIÓN: LECCIONARIO
    # ==========================================

    location = /leccionario {
        return 301 /leccionario/;
    }

    location /leccionario/ {
        alias /var/www/leccionario/;
        index index.html;
        try_files $uri $uri/ /leccionario/index.html;
    }

    location /leccionario/api/ {
        rewrite ^/leccionario/api/(.*) /api/$1 break;
        proxy_pass http://127.0.0.1:1080;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_connect_timeout 60s;
    }

    location /leccionario/ws/ {
        proxy_pass http://127.0.0.1:1080/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_connect_timeout 60s;
    }

    location ~* ^/leccionario/(.+\.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?))$ {
        alias /var/www/leccionario/$1;
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
