package com.leccionario.backend.user.domain;

import java.util.EnumSet;
import java.util.List;
import java.util.Set;

public final class RoleDefaults {

    public static final String ADMINISTRADOR = "ROLE_ADMINISTRADOR";
    public static final String DOCENTE = "ROLE_DOCENTE";
    public static final String ADMINISTRATIVO = "ROLE_ADMINISTRATIVO";
    public static final String ESTUDIANTE = "ROLE_ESTUDIANTE";

    private RoleDefaults() {
    }

    public static List<String> defaultRoles() {
        return List.of(ADMINISTRADOR, DOCENTE, ADMINISTRATIVO, ESTUDIANTE);
    }

    public static String normalize(String roleName) {
        String normalized = roleName == null ? "" : roleName.trim().toUpperCase().replace(' ', '_');
        return normalized.startsWith("ROLE_") ? normalized : "ROLE_" + normalized;
    }

    public static String description(String roleName) {
        return switch (normalize(roleName)) {
            case ADMINISTRADOR -> "Administra usuarios, perfiles, catalogos y supervision total.";
            case DOCENTE -> "Gestiona el leccionario y consulta informacion academica necesaria para docencia.";
            case ADMINISTRATIVO -> "Consulta modulos institucionales, auditoria y reportes sin modificar leccionarios.";
            case ESTUDIANTE -> "Perfil de consulta restringida para futuras funciones estudiantiles.";
            default -> "Perfil personalizado del sistema.";
        };
    }

    public static Set<PermissionCode> permissions(String roleName) {
        return switch (normalize(roleName)) {
            case ADMINISTRADOR -> EnumSet.of(
                    PermissionCode.USER_VIEW,
                    PermissionCode.USER_MANAGE,
                    PermissionCode.ROLE_VIEW,
                    PermissionCode.ROLE_MANAGE,
                    PermissionCode.ACADEMIC_VIEW,
                    PermissionCode.ACADEMIC_MANAGE,
                    PermissionCode.LESSONPLAN_VIEW,
                    PermissionCode.LESSONPLAN_MANAGE,
                    PermissionCode.EVALUATION_VIEW,
                    PermissionCode.EVALUATION_MANAGE,
                    PermissionCode.GRADE_VIEW,
                    PermissionCode.GRADE_MANAGE,
                    PermissionCode.LIBRETA_VIEW,
                    PermissionCode.LIBRETA_MANAGE,
                    PermissionCode.HISTORIAL_VIEW,
                    PermissionCode.CERTIFICADO_VIEW,
                    PermissionCode.CERTIFICADO_MANAGE,
                    PermissionCode.ASISTENCIA_VIEW,
                    PermissionCode.CONDUCTA_VIEW,
                    PermissionCode.MERITO_VIEW,
                    PermissionCode.MERITO_MANAGE,
                    PermissionCode.TUTORIA_VIEW,
                    PermissionCode.TUTORIA_MANAGE,
                    PermissionCode.BANCO_PREGUNTAS_VIEW,
                    PermissionCode.BANCO_PREGUNTAS_MANAGE,
                    PermissionCode.MATRICULA_VIEW,
                    PermissionCode.MATRICULA_MANAGE,
                    PermissionCode.NEE_VIEW,
                    PermissionCode.NEE_MANAGE,
                    PermissionCode.ADAPTACION_CURRICULAR_VIEW,
                    PermissionCode.ADAPTACION_CURRICULAR_MANAGE,
                    PermissionCode.DECE_VIEW,
                    PermissionCode.DECE_MANAGE,
                    PermissionCode.INSTITUTION_VIEW,
                    PermissionCode.INSTITUTION_MANAGE,
                    PermissionCode.CAMPUS_VIEW,
                    PermissionCode.CAMPUS_MANAGE,
                    PermissionCode.SHIFT_VIEW,
                    PermissionCode.SHIFT_MANAGE,
                    PermissionCode.CLASSROOM_VIEW,
                    PermissionCode.CLASSROOM_MANAGE,
                    PermissionCode.CALENDAR_VIEW,
                    PermissionCode.CALENDAR_MANAGE,
                    PermissionCode.INSTITUTION_CONFIG_VIEW,
                    PermissionCode.INSTITUTION_CONFIG_MANAGE,
                    PermissionCode.HR_VIEW,
                    PermissionCode.HR_MANAGE,
                    PermissionCode.HR_CONTRACT_VIEW,
                    PermissionCode.HR_CONTRACT_MANAGE,
                    PermissionCode.HR_VACATION_VIEW,
                    PermissionCode.HR_VACATION_MANAGE,
                    PermissionCode.HR_PERMISSION_VIEW,
                    PermissionCode.HR_PERMISSION_MANAGE,
                    PermissionCode.HR_TRAINING_VIEW,
                    PermissionCode.HR_TRAINING_MANAGE,
                    PermissionCode.STUDENT_WELFARE_VIEW,
                    PermissionCode.STUDENT_WELFARE_MANAGE,
                    PermissionCode.SCHOLARSHIP_VIEW,
                    PermissionCode.SCHOLARSHIP_MANAGE,
                    PermissionCode.CLUB_VIEW,
                    PermissionCode.CLUB_MANAGE,
                    PermissionCode.TRANSPORT_VIEW,
                    PermissionCode.TRANSPORT_MANAGE,
                    PermissionCode.FINANCE_VIEW,
                    PermissionCode.FINANCE_MANAGE,
                    PermissionCode.CASHIER_VIEW,
                    PermissionCode.CASHIER_MANAGE,
                    PermissionCode.INVOICE_VIEW,
                    PermissionCode.INVOICE_MANAGE,
                    PermissionCode.TUITION_VIEW,
                    PermissionCode.TUITION_MANAGE,
                    PermissionCode.RECEIVABLE_VIEW,
                    PermissionCode.RECEIVABLE_MANAGE,
                    PermissionCode.ASSET_VIEW,
                    PermissionCode.ASSET_MANAGE,
                    PermissionCode.ASSET_MAINTENANCE_VIEW,
                    PermissionCode.ASSET_MAINTENANCE_MANAGE,
                    PermissionCode.LIBRARY_VIEW,
                    PermissionCode.LIBRARY_MANAGE,
                    PermissionCode.LIBRARY_LOAN_VIEW,
                    PermissionCode.LIBRARY_LOAN_MANAGE,
                    PermissionCode.BI_DASHBOARD_VIEW,
                    PermissionCode.BI_REPORT_VIEW,
                    PermissionCode.BI_REPORT_EXPORT,
                    PermissionCode.NOTIFICATION_VIEW,
                    PermissionCode.NOTIFICATION_MANAGE,
                    PermissionCode.MESSAGE_VIEW,
                    PermissionCode.MESSAGE_MANAGE,
                    PermissionCode.PARENT_COMM_VIEW,
                    PermissionCode.PARENT_COMM_MANAGE,
                    PermissionCode.COMM_GROUP_VIEW,
                    PermissionCode.COMM_GROUP_MANAGE,
                    PermissionCode.AI_VIEW,
                    PermissionCode.AI_MANAGE,
                    PermissionCode.AI_PREDICT,
                    PermissionCode.AI_ANALYZE,
                    PermissionCode.REPORT_VIEW,
                    PermissionCode.REPORT_EXPORT,
                    PermissionCode.AUDIT_VIEW,
                    PermissionCode.SETTINGS_VIEW,
                    PermissionCode.SETTINGS_MANAGE,
                    PermissionCode.ANNOUNCEMENT_VIEW,
                    PermissionCode.ANNOUNCEMENT_MANAGE);
            case DOCENTE -> EnumSet.of(
                    PermissionCode.LESSONPLAN_VIEW,
                    PermissionCode.LESSONPLAN_MANAGE,
                    PermissionCode.EVALUATION_VIEW,
                    PermissionCode.EVALUATION_MANAGE,
                    PermissionCode.GRADE_VIEW,
                    PermissionCode.GRADE_MANAGE,
                    PermissionCode.LIBRETA_VIEW,
                    PermissionCode.LIBRETA_MANAGE,
                    PermissionCode.HISTORIAL_VIEW,
                    PermissionCode.CERTIFICADO_VIEW,
                    PermissionCode.ASISTENCIA_VIEW,
                    PermissionCode.CONDUCTA_VIEW,
                    PermissionCode.MERITO_VIEW,
                    PermissionCode.MERITO_MANAGE,
                    PermissionCode.TUTORIA_VIEW,
                    PermissionCode.TUTORIA_MANAGE,
                    PermissionCode.BANCO_PREGUNTAS_VIEW,
                    PermissionCode.BANCO_PREGUNTAS_MANAGE,
                    PermissionCode.MATRICULA_VIEW,
                    PermissionCode.NEE_VIEW,
                    PermissionCode.ADAPTACION_CURRICULAR_VIEW,
                    PermissionCode.DECE_VIEW,
                    PermissionCode.REPORT_VIEW,
                    PermissionCode.TEACHER_SELF_VIEW,
                    PermissionCode.ANNOUNCEMENT_VIEW,
                    PermissionCode.FINANCE_VIEW,
                    PermissionCode.CASHIER_VIEW,
                    PermissionCode.INVOICE_VIEW,
                    PermissionCode.TUITION_VIEW,
                    PermissionCode.RECEIVABLE_VIEW,
                    PermissionCode.NOTIFICATION_VIEW,
                    PermissionCode.MESSAGE_VIEW,
                    PermissionCode.PARENT_COMM_VIEW);
            case ADMINISTRATIVO -> EnumSet.of(
                    PermissionCode.ACADEMIC_VIEW,
                    PermissionCode.ACADEMIC_MANAGE,
                    PermissionCode.LESSONPLAN_VIEW,
                    PermissionCode.EVALUATION_VIEW,
                    PermissionCode.GRADE_VIEW,
                    PermissionCode.LIBRETA_VIEW,
                    PermissionCode.HISTORIAL_VIEW,
                    PermissionCode.CERTIFICADO_VIEW,
                    PermissionCode.CERTIFICADO_MANAGE,
                    PermissionCode.ASISTENCIA_VIEW,
                    PermissionCode.CONDUCTA_VIEW,
                    PermissionCode.MERITO_VIEW,
                    PermissionCode.TUTORIA_VIEW,
                    PermissionCode.BANCO_PREGUNTAS_VIEW,
                    PermissionCode.MATRICULA_VIEW,
                    PermissionCode.MATRICULA_MANAGE,
                    PermissionCode.NEE_VIEW,
                    PermissionCode.ADAPTACION_CURRICULAR_VIEW,
                    PermissionCode.DECE_VIEW,
                    PermissionCode.DECE_MANAGE,
                    PermissionCode.INSTITUTION_VIEW,
                    PermissionCode.INSTITUTION_MANAGE,
                    PermissionCode.CAMPUS_VIEW,
                    PermissionCode.CAMPUS_MANAGE,
                    PermissionCode.SHIFT_VIEW,
                    PermissionCode.SHIFT_MANAGE,
                    PermissionCode.CLASSROOM_VIEW,
                    PermissionCode.CLASSROOM_MANAGE,
                    PermissionCode.CALENDAR_VIEW,
                    PermissionCode.CALENDAR_MANAGE,
                    PermissionCode.INSTITUTION_CONFIG_VIEW,
                    PermissionCode.INSTITUTION_CONFIG_MANAGE,
                    PermissionCode.HR_VIEW,
                    PermissionCode.HR_MANAGE,
                    PermissionCode.HR_CONTRACT_VIEW,
                    PermissionCode.HR_VACATION_VIEW,
                    PermissionCode.HR_PERMISSION_VIEW,
                    PermissionCode.HR_TRAINING_VIEW,
                    PermissionCode.FINANCE_VIEW,
                    PermissionCode.FINANCE_MANAGE,
                    PermissionCode.CASHIER_VIEW,
                    PermissionCode.CASHIER_MANAGE,
                    PermissionCode.INVOICE_VIEW,
                    PermissionCode.INVOICE_MANAGE,
                    PermissionCode.TUITION_VIEW,
                    PermissionCode.TUITION_MANAGE,
                    PermissionCode.RECEIVABLE_VIEW,
                    PermissionCode.RECEIVABLE_MANAGE,
                    PermissionCode.ASSET_VIEW,
                    PermissionCode.ASSET_MANAGE,
                    PermissionCode.ASSET_MAINTENANCE_VIEW,
                    PermissionCode.ASSET_MAINTENANCE_MANAGE,
                    PermissionCode.LIBRARY_VIEW,
                    PermissionCode.LIBRARY_MANAGE,
                    PermissionCode.LIBRARY_LOAN_VIEW,
                    PermissionCode.LIBRARY_LOAN_MANAGE,
                    PermissionCode.BI_DASHBOARD_VIEW,
                    PermissionCode.BI_REPORT_VIEW,
                    PermissionCode.NOTIFICATION_VIEW,
                    PermissionCode.NOTIFICATION_MANAGE,
                    PermissionCode.MESSAGE_VIEW,
                    PermissionCode.MESSAGE_MANAGE,
                    PermissionCode.PARENT_COMM_VIEW,
                    PermissionCode.PARENT_COMM_MANAGE,
                    PermissionCode.COMM_GROUP_VIEW,
                    PermissionCode.COMM_GROUP_MANAGE,
                    PermissionCode.AI_VIEW,
                    PermissionCode.AI_ANALYZE,
                    PermissionCode.REPORT_VIEW,
                    PermissionCode.REPORT_EXPORT,
                    PermissionCode.AUDIT_VIEW,
                    PermissionCode.SETTINGS_VIEW,
                    PermissionCode.SETTINGS_MANAGE,
                    PermissionCode.ANNOUNCEMENT_VIEW,
                    PermissionCode.ANNOUNCEMENT_MANAGE);
            case ESTUDIANTE -> EnumSet.of(
                    PermissionCode.STUDENT_SELF_VIEW,
                    PermissionCode.LESSONPLAN_VIEW,
                    PermissionCode.GRADE_VIEW,
                    PermissionCode.HISTORIAL_VIEW,
                    PermissionCode.CERTIFICADO_VIEW,
                    PermissionCode.ASISTENCIA_VIEW,
                    PermissionCode.CONDUCTA_VIEW,
                    PermissionCode.MERITO_VIEW,
                    PermissionCode.TUTORIA_VIEW,
                    PermissionCode.ANNOUNCEMENT_VIEW,
                    PermissionCode.FINANCE_VIEW,
                    PermissionCode.INVOICE_VIEW,
                    PermissionCode.TUITION_VIEW,
                    PermissionCode.LIBRARY_VIEW,
                    PermissionCode.LIBRARY_LOAN_VIEW,
                    PermissionCode.NOTIFICATION_VIEW,
                    PermissionCode.MESSAGE_VIEW);
            default -> EnumSet.noneOf(PermissionCode.class);
        };
    }
}
